In [1]:
import pandas as pd
import os

In [7]:
path = r"C:\Users\farrkhan\Desktop\SQL\brazil dataset"

In [9]:
os.path.exists(path)

True

In [11]:
os.listdir(path)

['olist_customers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'product_category_name_translation.csv']

In [13]:
orders = pd.read_csv(
    path + r"\olist_orders_dataset.csv"
)

In [19]:
orders.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [21]:
orders.shape

(99441, 8)

In [23]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [25]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [27]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [29]:
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [31]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [33]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [37]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

## EDA 1 — Order Status Distribution
Business question:
"Bagaimana kondisi seluruh order di Olist?"

Kita mau tahu:
- berapa order delivered?
- berapa cancelled?
- apakah banyak order bermasalah?

In [45]:
orders['order_status'].value_counts() ## dataframe orders dari data set, SQL: FROM orders
## orders['order_status'] -> ambil 1 kolom: SQL: SELECT order_Status
## .value_counts() -> ambil frekuensi tiap kategori, SQL: COUNT(*) GROUP BY order_status
## jadi carabacanya = ambil kolom order_status dari tabel orders, lalu itung ada berapa kali SETIAP STATUS muncul

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [47]:
orders['order_status'].value_counts(normalize=True)

order_status
delivered      0.970203
shipped        0.011132
canceled       0.006285
unavailable    0.006124
invoiced       0.003158
processing     0.003027
created        0.000050
approved       0.000020
Name: proportion, dtype: float64

In [49]:
orders['order_status'].value_counts(normalize=True) * 100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

## EDA 3 — Range Waktu Dataset
Pertanyaan:
"Data ini mencakup tahun berapa?"

In [59]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [61]:
orders['order_status'].value_counts(normalize=True)*100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [63]:
orders['order_purchase_timestamp'].min(), orders['order_purchase_timestamp'].max() 
## SQL : MIN(blablalba) MAX(blablalba)

(Timestamp('2016-09-04 21:15:19'), Timestamp('2018-10-17 17:30:18'))

In [65]:
orders['order_month'] = (
    orders['order_purchase_timestamp']
    .dt.to_period('M')
)

In [77]:
monthly_orders = (
    orders
    .groupby('order_month')
    .size()
)

## SELECT
DATE_TRUNC('month', order_purchase_timestamp),
COUNT(*)
FROM orders
GROUP BY 1;

In [79]:
monthly_orders.head()

order_month
2016-09       4
2016-10     324
2016-12       1
2017-01     800
2017-02    1780
Freq: M, dtype: int64

In [81]:
monthly_orders = (
    orders
    .groupby('order_month')
    .size()
    .reset_index(name='total_orders')
)

In [92]:
monthly_orders.head() ## kalo di sql: SELECT
    ##order_month,
    ##COUNT(*) AS total_orders
##FROM orders
##GROUP BY order_month;

  order_month  total_orders
0     2016-09             4
1     2016-10           324
2     2016-12             1
3     2017-01           800
4     2017-02          1780

## Business question:
"Apakah jumlah order meningkat dibanding bulan sebelumnya?"

In [94]:
## buat kolom baru
monthly_orders['previous_orders'] = (
    monthly_orders['total_orders']
    .shift(1)
)

In [98]:
monthly_orders['growth'] = (
    (monthly_orders['total_orders'] -
     monthly_orders['previous_orders'])
    /
    monthly_orders['previous_orders']
    *100
)

In [100]:
monthly_orders.head()

  order_month  total_orders  previous_orders        growth
0     2016-09             4              NaN           NaN
1     2016-10           324              4.0   8000.000000
2     2016-12             1            324.0    -99.691358
3     2017-01           800              1.0  79900.000000
4     2017-02          1780            800.0    122.500000

## A. Apakah ada duplicate order?

In [103]:
##SQL: SELECT order_id, COUNT(*)
##FROM orders
## GROUP BY order_id
## HAVING COUNT(*) > 1;

In [105]:
orders['order_id'].duplicated().sum()

0

## Apakah ordeer unique?

In [107]:
orders['order_id'].nunique()

99441

In [109]:
orders.shape[0]

99441

In [112]:
## load tabel lain
customers = pd.read_csv(
    path + r"\olist_customers_dataset.csv"
)

In [114]:
order_items = pd.read_csv(
    path + r"\olist_order_items_dataset.csv"
)

In [116]:
payments = pd.read_csv(
    path + r"\olist_order_payments_dataset.csv"
)

In [122]:
customers.shape

(99441, 5)

In [124]:
order_items.shape

(112650, 7)

In [128]:
payments.shape

(103886, 5)

In [130]:
products = pd.read_csv(
    path + r"\olist_products_dataset.csv"
)

reviews = pd.read_csv(
    path + r"\olist_order_reviews_dataset.csv"
)

sellers = pd.read_csv(
    path + r"\olist_sellers_dataset.csv"
)

In [132]:
products.shape

(32951, 9)

In [134]:
reviews.shape

(99224, 7)

In [136]:
sellers.shape

(3095, 4)

In [138]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\farrkhan\anaconda3\lib\site-packages (2.0.30)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\farrkhan\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\farrkhan\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading psycopg2_binary-2.9.13-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
    --------------------------------------- 0.0/2.8 MB 667.8 kB/s eta 0:00:05
   --- ------------------------------------ 0.2/2.8 MB 2.0 MB/s eta 0:00:02
   ------- -------------------------------- 0.5/2.8 MB 3.5 MB/s eta 0:00:01
   --------------- ------------------------ 1.1/2.8 MB 5.7 MB/s eta 0:00:01
   ---------------------- ----------------- 1.5/2.8 MB 6.5 MB/s eta 0:00:01
   ----------------------------- ---------- 2.0/2.8 MB 7.1 MB/s eta 0:00:01
   ------------------------------------ --- 2.5/2.8 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  2.8/2.8 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 7.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.13

In [153]:
from sqlalchemy import create_engine

In [154]:
engine = create_engine(
    "postgresql://postgres:amgw11lh@localhost:5432/olist_analysis"
)

In [158]:
engine.connect()

In [160]:
orders.to_sql(
    'orders',
    engine,
    if_exists='replace',
    index=False
)

441

In [161]:
orders['order_month'] = orders['order_month'].astype(str)

In [162]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
order_month                              object
dtype: object

In [166]:
tables = {
    'customers': customers,
    'order_items': order_items,
    'payments': payments,
    'products': products,
    'reviews': reviews,
    'sellers': sellers
}

for table_name, df in tables.items():
    df.to_sql(
        table_name,
        engine,
        if_exists='replace',
        index=False
    )